run:
  run_description: ''
  store_dir: ..\data\results\oc_train
  tag: initial
data:
  meta_data_path: ..\data\youtube_dataset\video_data.json
  videos_dir: ..\data\youtube_dataset\videos
  transcripts_dir: ..\data\youtube_dataset\transcripts
  mouse_tracking_dir: ..\data\youtube_dataset\mouse_tracking
model:
  encoder_path: ..\data\pix2struct_vision_model
train:
  from_checkpoint: #Set to a run save path
  lr: 0.001
  w_decay: 0.01
  epoch_num: 2
  batch_size: 8
  logging_step: 2
  validation_step: 3